import * as dotenv from 'dotenv';
dotenv.config();
export const DB_HOST = process.env.DB_HOST || 'localhost';
export const DB_PORT = process.env.DB_PORT || 5432;
export const DB_USERNAME = process.env.DB_USERNAME || 'postgres';
export const DB_PASSWORD = process.env.DB_PASSWORD || 'redrose12';
export const DB_NAME = process.env.DB_NAME || 'postgres';
export const KAFKA_SERVER = process.env.KAFKA_SERVER || 'localhost:9092';
export const KAFKA_NAME = process.env.KAFKA_NAME || 'LENDING_SERVICE';
export const KAFKA_CLIENT = process.env.KAFKA_CLIENT || 'lending-KAFKA_CLIENT';
export const KAFKA_GROUPID = process.env.KAFKA_GROUPID || 'LENDING_GROUP';
